language: android
android:
        components:
                - build-tools-22.0.1
                - android-21
                - extra-google-m2repository
                - extra-android-m2repository
script: ./gradlew :library:testRelease --stacktrace --info
